### ISSUE TITLE
macOS installation instructions

### ISSUE THREAD

**Issue by jamesmurdza** [appcypher/monocore#51]
# Summary

## Problem

On macOS, krunvm needs to be installed.

## Solution

Should this be added to the installation instructions?

```
brew tap slp/krun
brew install krunvm
```

**Comment by appcypher** [comment]
You are right; I forgot to add that. However, I plan to improve the installation experience in the near future. The build steps should really be for development only.

Thank you for checking out the project.

**Comment by jamesmurdza** [comment]
More notes:

- I had to run **`sudo`**`make build`, otherwise I get the error `Error: lsetxattr /Volumes/krunvm/root/vfs: permission denied` when building libkrun.
- I had to install cargo.

After that, it worked. 🙂

**Comment by appcypher** [comment]
Great feedback. The example configs might not work as well. They are always outdated because I can't stop changing how they work 😅 

I will be focus on fixing all of that in the next few days.
